#!/bin/sh

# Read all about UCI defaults at
# https://openwrt.org/docs/guide-developer/uci-defaults

# Note that scripts in /etc/uci-defaults will get executed at *every* first
# boot (i.e. after both factory install as well as upgrades),
# possibly overwriting already existing values!
# scripts in this dir should *not* be executable
# set network.lan.ipaddr='192.168.178.1'
# set wireless.@wifi-device[0].disabled='0'
# set wireless.@wifi-iface[0].ssid='OpenWrt0815'
# add dhcp host
# set dhcp.@host[-1].name='bellerophon'
# set dhcp.@host[-1].ip='192.168.2.100'
# set dhcp.@host[-1].mac='a1:b2:c3:d4:e5:f6'
# rename firewall.@zone[0]='lan'
# rename firewall.@zone[1]='wan'
# rename firewall.@forwarding[0]='lan_wan'

uci set wireless.@wifi-device[0].disabled="0"
uci set wireless.@wifi-iface[0].disabled="0"
uci set wireless.@wifi-iface[0].ssid="OpenWrt"
uci set wireless.@wifi-iface[0].key="changemeplox"
uci set wireless.@wifi-iface[0].encryption="psk2"
uci commit wireless


exit 0
